### PR TITLE
Fix for: Centered captioned images are not centered - issue #87

### PR DESCRIPTION
**Pull request by khleomix**
contributor: @khleomix

The image centering issue is not caused by CSS but rather by the injected hard-coded style added by the caption shortcode. Add a function to address that. 

For the style of the caption, it should be the same as the Gutenberg inserted one now. This might change if #77 can be addressed.

### CODE REVIEW

**Comment by joyously** [comment]
> The image centering issue is not caused by CSS but rather by the injected hard-coded style added by Gutenberg.

This is not the case, because I am not using Gutenberg.

**Comment by joyously** [comment]
If a user chose a size for the image, and core is adding that size to the style tag, the user will get an image the size he chose. If you remove the size with this filter, what will he get? This issue is about centering, not about changing the size.

**Comment by khleomix** [comment]
@joyously sorry, my mistake. The injected style is added by the wp-caption shortcode

**Comment by khleomix** [comment]
@joyously I've tested with and without Gutenberg and with different image sizes and tested with left and right aligned images and in mobile and tablet without the filter and everything checks out. I've checked out themes and created themes that disable the filter as well without any issues. I could not find any other cause for the centering problem aside from that filter - it might be caused by CSS and might be related to #77. I'll check this further tomorrow when I wake up.

**Comment by khleomix** [comment]
Furthermore, the Gutenberg image block outputs the same code but without the injected style and that seems to work pretty well.

**Comment by kjellr** [comment]
The issue doesn't seem to be fixed here for me. I'm also seeing a caption alignment bug that I thought we fixed in #145. 🤔 

**Front End:**
screen shot 2018-10-27 at 12 58 51 pm

**Editor:**
screen shot 2018-10-27 at 12 58 08 pm

The margin for the `align center` class appears to be overridden by [this global rule](https://github.com/WordPress/twentynineteen/blob/8d47b1b791436bae516a1668828d35f1374d3df5/sass/blocks/_blocks.scss#L6).

**Comment by kjellr** [comment]
I'm going to close this one, since #380 took care of the centering issue. I'll borrow code from this to sync up the caption styles in a separate PR.  

Thanks everyone!

**Pull request closed without merging**
