### PR TITLE
Feature/customizer primary color

### PR DESCRIPTION
**Pull request by fabiankaegy**
Work in progress of #149

### CODE REVIEW

**Comment by fabiankaegy** [comment]
@killermann this is the current state

**Comment by designsimply** [comment]
@fabiankaegy thank you for working on this! I noticed #113 looks like similar work and was wondering if you'd like to keep #113 open or consolidate to #154? I know it's a best practice to use smaller, incremental PRs in general but wanted to ask you for this case.

**Comment by fabiankaegy** [comment]
@designsimply I first worked on #113 and because @kjellr said that customizing the primary color of all elements should be done in a separate PR I opened this one. But If we are committing to this we can close #113 all together because this is based on the work there.

**Comment by designsimply** [comment]
Ace. I vote for consolidating to #154 then! 😊

**Comment by kjellr** [comment]
> I first worked on #113 and because @kjellr said that customizing the primary color of all elements should be done in a separate PR I opened this one. But If we are committing to this we can close #113 all together because this is based on the work there.

That sounds great — I definitely think it makes sense to commit to customizing all elements, so it makes sense to consolidate these. Thanks all!

**Pull request closed without merging**
