### PR TITLE
Add Japanese language support

### PR DESCRIPTION
**Pull request by nielslange**
Add Japanese (js: 日本語) language support due to #29.

### CODE REVIEW

**Comment by mirucon** [comment]
Why would you use "Hiragino Kaku Gothic Pro" for this? To talk about some details about Japanese font in macOS, there are 3 kinds of the Hiragino Kaku Gothic font (macOS default Japanese font) bundled in macOS Mojave, "Hiragino Kaku Gothic Pro", "Hiragino Kaku Gothic ProN", and "Hiragino Sans". The "ProN" font has created based on JIS2004, the newer standard of Japanese character compared to the base of "Pro". And "ProN" is the default font from OS X 10.5 and iOS (forgot what version, but probably just as old as OS X 10.5) to OS X Yosemite (10.10) and iOS 8. 

And the "Hiragino Sans" was introduced in macOS El Capitan (10.11), the same time of the San Francisco font was introduced, and it's been the default macOS Japanese font since then. And the big advantage of Hiragino Sans is it covers weight 100 to 900 although Pro/ProN only cover 300 and 600 weight (iOS does not have all of them though, but it has more than Pro/ProN). So I would not recommend using either "Pro" or "ProN". They are not 2019's.

However just specifying "Hiragino Sans" in font-family isn't really the answer in my opinion. I personally do not like the idea of using Hiragino fonts alphabets, because it's not as good as other alphabet fonts bundled in macOS. What I suggest is to use Hiragino Sans font with San Francisco (which can be specified via -apple-system and BlinkMacSystemFont). It's the pair of San Francisco and Hiragino Sans is just same as macOS system default so people should have gotten used to it.

Therefore this is what I suggest using for Japanese: 

```
-apple-system, BlinkMacSystemFont, "Helvetica Neue", "Hiragino Sans", Meiryo, sans-serif;
```

And use this for the theme body including input and textareas.

The opinion about the Hiragino alphabets could be very personal, though, I believe the idea of using "Hiragino Sans" is a correct thing in 2019.

**Comment by nielslange** [comment]
@mirucon Thanks for your feedback. I used that particular font based on a discussion that took place in https://github.com/WordPress/twentyseventeen/pull/155. I‘m happy to adjust the font according to your suggestion. Do you know if Windows systems support "Hiragino Sans" as well? And wouldn’t it be better to use the following order:

```
-apple-system, BlinkMacSystemFont, "Hiragino Sans", Meiryo, "Helvetica Neue", sans-serif;
```

**Comment by mirucon** [comment]
Unfortuately the Hiragino Sans is not supported in Windows. However "Meiryo" is the one bundled in Windows Vista or later. Some people might argue with whether we should use Yu Gothic (which it's bundled in Windows 8.1+) though, I'm against using this font for websites since it looks too thin on some browsers, especially screens with low resolution.

Since the meiryo fonts was designed as the extended version of Verdana, the alphabets of this font is not bad and I don't really think we should use separate font for alphabets in Meiryo. So what you suggested looks good to me :)

**Comment by nielslange** [comment]
@mirucom Thanks for letting me know. I’ll make that change later today.

**Comment by nielslange** [comment]
Closed in favour of #383

**Pull request closed without merging**
