### PR TITLE
Feature/min height emoji fix

### PR DESCRIPTION
**Pull request by fabiankaegy**
fixes issue mentioned in issue #105

### CODE REVIEW

**Comment by fabiankaegy** [comment]
This fix introduces an error where in the admin avatar image also gets the `min-height` Banause of the specificity of the `:not()`selector. Working on a fix for that

**Comment by LittleBigThing** [comment]
It should be `min-height`.

**Comment by fabiankaegy** [comment]
@LittleBigThing thanks for noticing. Stupid mistake  😂

**Comment by kjellr** [comment]
@fabiankaegy did you try just removing the `min-height` entirely? I'm not 100% sure it's needed.

**Comment by allancole** [comment]
Yup, @fabiankaegy you can remove `min-height` entirely from the `img` selector—it’s unnecessary. 

Take that out and we can go ahead and merge this PR ;-)

**Pull request merged**
