### PR TITLE
Align password input and submit button

### PR DESCRIPTION
**Pull request by briannaorg**
Fix for issue #298. 

Since there’s no specific styling for just this use case, and a fix
requires making changes to the global styles for inputs and buttons, I
just aligned the submit button type vertically and slightly adjusted
the padding so it’s equal to the height of all inputs, as well as
slightly adjusting the vertical padding of the inputs to match.

WordPress.org: @technosiren

### CODE REVIEW

**Comment by briannaorg** [comment]
@kjellr no problem. style-editor.scss didn't have explicit padding on its button styles so I left it as-is. _blocks.scss has been updated to match _buttons.scss.

**Comment by briannaorg** [comment]
@allancole - the vertical padding inside the inputs was reduced (shorter inputs), and the vertical padding of the buttons very slightly increased until they matched, after I vertically-aligned the submit button to the bottom of the input.  I tried to use a light touch on this one since it affects global styles, but @kjellr, let me know how you want to proceed.

**Comment by kjellr** [comment]
> I assumed the input form height would be lowered to match the height of the button (instead of the other way around). I think I’d prefer shorter inputs over taller buttons, but I’ll let @kjellr make final call on this.

I'd originally assumed that'd be the most natural route too, but this actually feels pretty comfortable. It also turns out our global button sizes on the front end were unintentionally about 8px shorter than the buttons in the editor. 😄 So the changes in this PR not only fix the input field height, but they sort that out too, bringing greater alignment between the front and back end. Seems like a solid fix to me. 👍 

@briannaorg — would you mind fixing up that one conflict? I don't think `style.css.map` actually needs to be committed in this case. Once that's done we can go ahead and merge this.

**Comment by briannaorg** [comment]
All set - I've merged master with this branch and omitted the .map file. Thanks @kjellr!

**Comment by kjellr** [comment]
Thanks @briannaorg! I think the `.map` file is still included here... would you mind double checking that one?

**Comment by briannaorg** [comment]
Thanks @kjellr - I am still getting used to the Github Desktop interface, the .map file has been deleted and committed to the branch.

**Pull request merged**
