### PR TITLE
Fix Issue #282 Regarding SubMenu Container width

### PR DESCRIPTION
**Pull request by c4rl0sbr4v0**
This PR fixes Issue: [Issue #282 ](https://github.com/WordPress/twentynineteen/issues/282)

I will let you know as soon I can test it on IE11, but a display table should fix it.
screenshot 2018-10-25 at 10 43 32

### CODE REVIEW

**Comment by c4rl0sbr4v0** [comment]
This is how it is seen in IE 11
IE11

**Comment by c4rl0sbr4v0** [comment]
Awesome! Didn't know if I should change or not that styling, that's why I didn't :-)

**Comment by afercia** [comment]
I've noticed now that, when using a keyboard, the sub-menus appear thanks to `:focus-within` on their `.menu-item-has-children`.  Worth reminding `:focus-within` doesn't work on Edge and IE11 so when using the keyboard on those browsers the sub-menus can't be accessed in any way 😞 
/Cc @kjellr

**Comment by kjellr** [comment]
Thanks, @afercia — since `:focus-within` was used prior to this PR, would you mind filing a separate issue for that one?

**Comment by westonruter** [comment]
We should to add a polyfill for IE to toggle a `.focus-within` class similar to how core themes have done this .

Note that users who have JS disabled in their browsers would still have a keyboard-inaccessible nav menu, but this would have been the case for all core themes until now. With `:focus-within`, nav sub-menus are accessible for the first time for non-IE/Edge browsers which have JS disabled. So it's a both/and not an either/or situation.

**Comment by afercia** [comment]
@kjellr sure, see https://github.com/WordPress/twentynineteen/issues/266#issuecomment-433308499 where coincidentally I've just suggested to try a polyfill.

**Pull request merged**
