### PR TITLE
Fix placement of translators: comments

### PR DESCRIPTION
**Pull request by Ismail-elkorchi**
For translators comments to be recognized, they must be on the line directly before the gettext call.

### CODE REVIEW

**Comment by Ismail-elkorchi** [comment]
Another solution is to store the printf ( since it's called twice ) in a variable and echo it.

The code will look like something like this : 
```
<?php
	/* translators: 1: comment date, 2: comment time */
	$comment_timestamp = printf( __( '%1$s at %2$s', 'twentynineteen' ), get_comment_date( '', $comment ), get_comment_time() );
?>
<time datetime="<?php comment_time( 'c' ); ?>" title="<?php echo $comment_timestamp; ?>">
	<?php echo $comment_timestamp; ?>
</time>
```

**Comment by joyously** [comment]
It would have to change from printf to sprintf.

**Comment by Ismail-elkorchi** [comment]
> It would have to change from printf to sprintf.

You're right! I changed my comment to reflect that.

**Comment by Ismail-elkorchi** [comment]
@kjellr Can you please review this PR, and tell me which approach is the best. It's the one committed in the PR, or the one suggested in the comment above ? So I can update this PR.

**Comment by allancole** [comment]
> Another solution is to change the `printf` call to `sprintf`, store it in `$comment_timestamp` ( since it's called twice ) and echo it.

Yup, I think this the right way to go @Ismail-elkorchi . Make that change and we’ll go ahead and merge this in 👍

**Comment by Ismail-elkorchi** [comment]
Thank you @allancole for your review. I made the change requested, it should be good to merge 👍

**Pull request merged**
