### PR TITLE
Fixed audio player overlaping post/page container

### PR DESCRIPTION
**Pull request by mmaumio**
Using self hosted Audio file with audio shortcode using Media Element js on any post/page overlaps the entire post/page content area.
Fixed the issue here.

WordPress.org: mmaumio

### CODE REVIEW

**Comment by nielslange** [comment]
@mmaumio The fix looks great. Could you also add the change to the SCSS file? Otherwise, your change would get lost the first time the SCSS file gets rendered.

**Comment by mmaumio** [comment]
> @mmaumio The fix looks great. Could you also add the change to the SCSS file? Otherwise, your change would get lost the first time the SCSS file gets rendered.

Thank You.
Just did.

Please let me know if there's anything else.

**Comment by kjellr** [comment]
👋 I got fix in alongside #185, since it turned out they actually needed mostly the same code. 🙂 

Thanks for your help! I've [added you](
https://github.com/WordPress/twentynineteen/pull/185/commits/13371b31ee8e3bc4a9391996a32cffa5ee8eb322) to the contributors file!

**Comment by mmaumio** [comment]
Thank you for accepting my code and adding me to the Contributors.
It's a privilege :)

**Pull request closed without merging**
