### PR TITLE
fixed CSS cross-browser support

### PR DESCRIPTION
**Pull request by shahjehanali1**
Cross browser support added

### CODE REVIEW

**Comment by kjellr** [comment]
Hey @shahjehanali1, can you give a little more background to this PR? What cross browser support is being added?

**Comment by shahjehanali1** [comment]
Hey @kjellr, I've added CSS browser prefixes it this branch

**Comment by nielslange** [comment]
@shahjehanali1 and @kjellr I thought by using `autoprefixer` and `postcss-cli` we would have cross-browser support by default. Have I missed something here? While your contribution is great, @shahjehanali1, I would instead proceed with an automated solution.

**Comment by shahjehanali1** [comment]
@nielslange , @kjellr There is no  CSS browser prefixes in  CSS of twentynineteen theme.

**Comment by allancole** [comment]
We are now using `autoprefixer` in our build tool, so this change is no longer needed. Graciously closing this PR.

**Pull request closed without merging**
