### PR TITLE
Add non-latin language support

### LINKED ISSUE #29: Support for non-latin font fallbacks
Looking at the [_fonts.scss](https://github.com/WordPress/twentynineteen/blob/master/sass/variables-site/_fonts.scss), most of the specified fonts -- as I am aware -- only support Latin alphabets.  They do not support or only very limited support for non-latin alphabets.

In addition to that, serif fonts are specified as the primary body font. 

`$font__body: "Hoefler Text", "Baskerville Old Face", Garamond, "Times New Roman", serif;`

In Japanese, non-serif fonts are more commonly used on the web. If serif fonts are used, we need to consider the choice of them very carefully, else readability and aesthetics become absolutely terrible.

Are there any similar cases in any other languages? I am not sure.

The same issue regarding better support for non-latin font fallbacks was raised and applied in the development of twentyseventeen https://github.com/WordPress/twentyseventeen/issues/59

I would like to raise this issue for same matter to be considered in Twentynineteen too. 

---

_19-Oct Edit by designsimply_

List of alphabets supported in `twentyseventeen` that we also want to try support:

1. Cyrillic ( https://github.com/WordPress/twentyseventeen/pull/364 )
1. Greek ( https://github.com/WordPress/twentyseventeen/pull/366 )
1. Hebrew ( https://github.com/WordPress/twentyseventeen/pull/294 )
1. Arabic ( https://github.com/WordPress/twentyseventeen/pull/398 )
1. Vietnamese ( See [twentyseventeen/59 (comment)](https://github.com/WordPress/twentyseventeen/issues/59#issuecomment-254065128) and [twentyseventeen/59 (comment)](https://github.com/WordPress/twentyseventeen/issues/59#issuecomment-260561023) )
1. Thai ( https://github.com/WordPress/twentyseventeen/pull/93 )
1. Japanese ( https://github.com/WordPress/twentyseventeen/pull/155 )
1. Korean ( https://github.com/WordPress/twentyseventeen/pull/286 )
1. Chinese ( https://github.com/WordPress/twentyseventeen/pull/359 )
1. Devanagari ( https://github.com/WordPress/twentyseventeen/pull/403 )
1. Gujarati ( https://github.com/WordPress/twentyseventeen/pull/404 )

Checklist for `twentynineteen` PRs:

- [ ] Cyrillic (~#343~ #383)
- [ ] Greek (~#344~ #383)
- [ ] Hebrew (~#345~ #383)
- [ ] Arabic (~#346~ #383)
- [ ] Vietnamese (~#347~ #383)
- [ ] Thai (~#348~ #383)
- [ ] Japanese (~#341~ #383)
- [ ] Korean (~#349~ #383)
- [ ] Chinese (~#351~ #383)
- [ ] Devanagari (~#352~ #383)
- [ ] Gujarati (~#353~ #383)

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #29 

Add non-latin language support for:

- Arabic —> ar: العربية, ary: العربية المغربية, azb: گؤنئی آذربایجان, ckb: كوردی‎, fa-IR: فارسی, haz: هزاره گی, ps: پښتو
- Chinese —> zh_HK: 香港中文版, zh_TW: 繁體中文, zh_CN: 简体中文
- Cyrillic —> be: Беларуская мова, bg_BG: Български, kk: Қазақ тілі, mk_MK: Македонски јазик, mn: Монгол, ru-RU: Русский, sah: Сахалыы, sr_RS: Српски језик, tt_RU: Татар теле, uk: Українська
- Devanagari —> bn_BD: বাংলা, hi_IN: हिन्दी, mr: मराठी, ne_NP: नेपाली
- Greek —> el: Ελληνικά
- Gujarati —> gu: ગુજરાતી 
- Hebrew —> he_IL: עִבְרִית
- Japanese —> js: 日本語
- Korean —> ko_KR: 한국어
- Thai —> th: ไทย
- Vietnamese —> vi: Tiếng Việt

### CODE REVIEW

**Comment by naokomc** [comment]
@nielslange 
I noticed there are some locale codes with underscores instead of hyphens. Shouldn't they all be using hypens?

(e.g. https://tt.wordpress.org/ has `lang="tt-RU"` in the code but the css says `lang="tt_RU"`)

**Comment by nielslange** [comment]
> @nielslange
> I noticed there are some locale codes with underscores instead of hyphens. Shouldn't they all be using hypens?
> 
> (e.g. https://tt.wordpress.org/ has `lang="tt-RU"` in the code but the css says `lang="tt_RU"`)

Good catch, @naokomc! They should all be hyphens. I'll fix this issue now.

**Comment by nielslange** [comment]
@naokomc The ISO language codes should be fixed with my latest push. Thanks again for bringing this to my attention. 😉

**Comment by kjellr** [comment]
Thanks @yuliyang! I pushed another update that  should address this. Instead of globally specifying the font family like we were doing before, this PR now uses a wrapper to only target site content: `html[lang="ar"] .site *` on the front end, and `html[lang="ar"] .wp-block *` in the editor. Mind giving this another test?

**Comment by nielslange** [comment]
@yuliyang Also, as discussed earlier today on Slack, I've included your changes regarding separate font families for _Chinese (Hong Kong)_, _Chinese (Taiwan)_ and _Chinese (China)_. Thanks again for your contribution and would be great if you could run a quick test, as mentioned by @kjellr in https://github.com/WordPress/twentynineteen/pull/383#issuecomment-435407280.

**Comment by yuliyang** [comment]
Tested and works perfectly. Thanks, @kjellr & @nielslange !

**Comment by miminari** [comment]
I'm Japanese. Thank you for thinking about non-latin language.
I think it is too early to using Serif font in Japanese. So, I think this fallback is needed.

However, I think this PR convert every text to sans-serif by an asterisk. I don't know why this theme uses 2 font types and the purpose, but I think this fallback for the people who don't know how to change the font-family by themselves very well.

But, by this PR, they maybe have to exchange something (ex. `pre` ) in the customizer by themselves. I think it may be hard work for them.

I know it's also important the code maintainability and lightness of the file size. But we should think about why we make this fallback.

**Comment by nielslange** [comment]
Thanks for your comment, @miminari. Would you mind creating a separate issue for this, add a screenshot and reference to this issue?

**Comment by miminari** [comment]
OK, I will try it. Thank you for your replay.

**Comment by mako09** [comment]
I've just tested wordpress-5.0-beta5. In the classic block of the Guteberg editor, toolbar icons are garbled. Its cause is in this PR including asterisk and !important.

I can't help thinking that this PR is wrong.

ss_2018-11-16_10-37-15

**Pull request merged**
