### PR TITLE
Corrected column math in galleries - issue #91

### PR DESCRIPTION
**Pull request by briannaorg**
contributor: technosiren

1) If columns are being displayed inside .entry-content, as in the gallery use case, then vw is not the correct unit of measure for the column map because the entire viewport isn't available. I switched the columns map to use percentages instead, so it's sized to its container. 

2) As pretty as the column map is in _columns.scss, the math doesn't actually work. 

A single-column gallery is not equivalent to a single column width - it's equal to 12 column widths. I adjusted the math in the loop inside _galleries.scss to accommodate this, and update the map key in _columns.scss to accommodate decimal values for the actual widths required. 

While testing, I discovered that the values returned for the 7 and 9 column galleries weren't mappable due to decimal places. So I ended up eliminating the columns map entirely from _galleries.scss and left it as the original map with viewport units, not currently in use.

3) I included the gutters and inherited text alignment from the .gallery-item container so every iteration of gallery columns 1-9 is sized appropriately for its container.

### CODE REVIEW

**Comment by joyously** [comment]
How do I test this with the other CSS changes?

**Comment by joyously** [comment]
Yeah, so I'd have to do that for the other changes too, to test them together...

**Comment by briannaorg** [comment]
> Yeah, so I'd have to do that for the other changes too, to test them together...

Not if you first checkout my branch with the fix into your working directory - then you're testing only the code in that branch.

**Comment by joyously** [comment]
I know how to test one at a time. I'm trying to test them together.

**Comment by briannaorg** [comment]
Sorry, maybe posting links to the issues you're trying to test with would help - I can either merge my fixes with those or we can ask @kjellr for testing guidance.

**Comment by kjellr** [comment]
Which other changes are you trying to test this with, @joyously? In general, we tend to test changes one at a time, within individual branches.

**Comment by joyously** [comment]
I think it was the similar issues: #59 and #58

**Comment by briannaorg** [comment]
I believe those are coming from Gutenberg, however I have not yet been able to duplicate them.

**Comment by briannaorg** [comment]
@allancole @kjellr this one is finally conflict-free and ready to go.

**Pull request merged**
