### PR TITLE
Remove POT file

### PR DESCRIPTION
**Pull request by ocean90**
POT files are no longer required on wordpress.org.

### CODE REVIEW

**Comment by 00travelgirl00** [comment]
Is it possible to translate the theme, bevor it goes in the directory? I Would like to translate it and test the translator and if the strings are fully ready for translation.

**Comment by ntwb** [comment]
It's available now for translation:
> https://translate.wordpress.org/projects/wp-themes/twentynineteen

**Comment by grappler** [comment]
@ntwb But does that include the latest changes on GitHub?

**Comment by allancole** [comment]
Thanks @ocean90, that should’ve been removed a while ago :-(

**Pull request merged**
