### PR TITLE
Fix critical GitHub security issue

### PR DESCRIPTION
**Pull request by allancole**
This PR addresses a critical security issue found in a dependency related to our 
- Remove all references to flatmap-stream dependency
- Remove all references to event-stream dependency
- See warning from GitHub for more info: https://github.com/dominictarr/event-stream/issues/116

### CODE REVIEW

**Comment by TwoAbove** [comment]
@allancole Pretty sure that the recommendation is version `3.3.4`, not `3.3.5`

**Comment by allancole** [comment]
@TwoAbove I went ahead an just removed it entirely. This seemed to have no negative effects on the build script. 

Please test this and let me know if you discover any issues with it being removed completely :-)

**Comment by TwoAbove** [comment]
@allancole Let me clone and check

**Comment by TwoAbove** [comment]
@allancole 
Looks good!
```
twoabove@MantaRay-u:/media/twoabove/SSD/Work/twentynineteen$ npm ls event-stream flatmap-stream
twentynineteen@1.0.0 /media/twoabove/SSD/Work/twentynineteen
└─┬ npm-run-all@4.1.3
  └─┬ ps-tree@1.1.0
    └── event-stream@3.3.5 
```

**Comment by TwoAbove** [comment]
@allancole https://www.npmjs.com/package/npm-run-all pulls flatmap-stream. Updating to 4.1.5 fixes that

**Comment by ntwb** [comment]
Bumping `npm-run-all` to `4.1.5` should resolve the issue (I've done this myself on various repos yesterday).

Aside: To get a "safe" version of `events-stream` it must be bumped to at least 4.x

**Comment by allancole** [comment]
Should be all fixed in that last commit @TwoAbove @ntwb 👍

**Pull request merged**
