### PR TITLE
Add custom `sizes` attribute to post body images.

### PR DESCRIPTION
**Pull request by mor10**
Addresses #50. Replaces #411.

Dependent on https://github.com/WordPress/gutenberg/pull/11973.

Add custom `sizes` attribute to images in post/page body. Provides custom values for "regular" and `wide` images and sets `full` images to the default.

### Todo:
- [ ] Test left/right aligned images (smaller than regular width.
- [ ] Test gallery images.

### CODE REVIEW

**Comment by mor10** [comment]
cc @azaozz @joemcgill @mtias

**Comment by mor10** [comment]
Now contingent on https://core.trac.wordpress.org/ticket/45407 and https://core.trac.wordpress.org/ticket/45406

**Comment by mor10** [comment]
Updated PR to reflect how the filter will eventually work once the block attributes for the containing block are available in the `wp_calculate_image_sizes` filter.

cc @joemcgill

**Comment by kjellr** [comment]
This PR has been ported over as a patch on this Trac ticket: https://core.trac.wordpress.org/ticket/45985

**Pull request closed without merging**
