### PR TITLE
Updating the Twenty Nineteen description in the .scss file

### PR DESCRIPTION
**Pull request by jobthomas**
Using mostly wording of @allancole  in the intro post here: https://make.wordpress.org/core/2018/10/16/introducing-twenty-nineteen/

(Haven't compiled yet @allancole)

### CODE REVIEW

**Comment by jobthomas** [comment]
Thanks @allancole and @kjellr

**Comment by laurelfulford** [comment]
Just a heads up: I've created an issue, #744, to cover updating style.css, style.scss and readme.txt to match the files that needed updating for the WordPress 5.0.2 release (related ticket here: https://core.trac.wordpress.org/ticket/45681).

I didn't touch the README.md there, because it doesn't exist in Core SVN, but it would be good to get it updated again to sync things up :) With the next release, Twenty Nineteen will be at 1.1.

**Comment by laurelfulford** [comment]
I've committed the above to Core in https://core.trac.wordpress.org/changeset/44377

**Comment by kjellr** [comment]
Merging this, since it's been committed to Trac already. 🚢

**Pull request merged**
