### PR TITLE
Fix indentation

### PR DESCRIPTION
**Pull request by B-07**
As same as other files

### CODE REVIEW

**Comment by 2ndkauboy** [comment]
You should probably remove the closig PHP tag (as in the other files).

**Comment by B-07** [comment]
@2ndkauboy Yes! Fixed! Thanks!

**Comment by kjellr** [comment]
@B-07 — I think this was taken care of via #167. Can you confirm?

**Comment by B-07** [comment]
Yes, Looks fine! Closing this.

**Pull request closed without merging**
