### PR TITLE
add starter content

### PR DESCRIPTION
**Pull request by LittleBigThing**
Related to #216 

A first, rough take on adding Gutenberg compatible starter content to the theme

### CODE REVIEW

**Comment by joyously** [comment]
Can you change the content out to something that's actually useful for a new site? I know you want to introduce the theme, but it will be the default theme for awhile, and new sites don't need that. They need a nice way to start their site.

**Comment by LittleBigThing** [comment]
@joyously Of course, but as I mentioned above, I would love to have suggestions on the content we’ll use, blocks as well as text.

Do we go for a blog example or for for a business site? Maybe there are clearer directions for this already.

**Comment by joyously** [comment]
There aren't. We just have to make it up as we go. That's why I asked for what this theme was targeting, and the answer I got was basically "everything" or "highlight GB".

For starter content, it makes more sense to create Pages and set a home page than it does to create Posts and show the blog on home, even though WP is blogging software. The user should not have to "undo" the starter content. It should be more like fill in the blanks.

**Comment by allancole** [comment]
I haven’t tested this yet @LittleBigThing, but thanks for getting this started! 

Regarding what the content should be, I think we might already have some good starter content we can borrow from our early mocks. Maybe these could work: 

A Blog **Post**: https://cloudup.com/ijfvuiEe5ne
A Business **Page**: https://cloudup.com/i9tJJqeq47A

I also have this content built out with Gutenberg Blocks on my local testing site. I could send that to you as an WP export file or just share the raw Gutenberg markup, if you want. 

> The user should not have to "undo" the starter content. It should be more like fill in the blanks.

Agreed and with Gutenberg, it’s super easy to swap out images/text.

**Comment by LittleBigThing** [comment]
@allancole cool, welcome to send me that raw content in one way or another so I can “quickly” update the PR.

**Comment by allancole** [comment]
Here goes it @LittleBigThing :-) 

**Blog Post Content**
https://gist.github.com/allancole/4131162468ccc5da8dbca24478cd52e4

**Business Content**
https://gist.github.com/allancole/2f69f6a9ad1f9fcc891ff269f00401ec

**Image Assets**
https://www.dropbox.com/s/54exvar23ci2g4h/Assets.zip?dl=1

**Comment by WarenGonzaga** [comment]
I have suggestion, can we use "Gutenberg Ipsum" a dummy text for the starter content? Something link an alternative for Lorem Ipsum. Reference: http://mentalfloss.com/article/61003/10-funnier-alternatives-lorem-ipsum

**Comment by LittleBigThing** [comment]
So a late update, if not too late.

I was stuck at adding images contained in the post content, such as a background image for a Cover block (see [proposed starter content design](https://cloudup.com/i9tJJqeq47A)).

As an example, the cover block has this HTML markup:

```
<!-- wp:cover {"url":"http://gutenberg.development/wp-content/uploads/2018/10/office-space.png","align":"full","contentAlign":"left","id":3370} -->
<div class="wp-block-cover has-background-dim has-left-content alignfull" style="background-image:url(http://gutenberg.development/wp-content/uploads/2018/10/office-space.png)"><p class="wp-block-cover-text">Digital strategies for unique small businesses</p></div>
<!-- /wp:cover -->
```

So we need a URL and an id to have this image in a cover block. It seems that we can insert a URL, but I am not sure we can get an attachment ID there. But is it needed? Can someone test it if this is in any way an interesting addition so last minute.

Another thing I noticed is that starter content for a page/post needs to have a title (so I had to add something). In the proposed design, there is no page title, but a cover image with text (in a paragraph) that functions as page title. In Gutenberg there is no way of setting the text on a cover image as a heading, which we would probably need. 

**We could slightly adjust the design and use a featured image with page title instead of the cover block?**

**Comment by LittleBigThing** [comment]
To summarize what's added here as starter content:

- a custom front page built with Gutenberg
- a Blog page to display posts
- an About page (core starter content), with a featured image
- a Contact page
- 2 attachments: a landscape and a portrait placeholder image
- 2 menus: a main menu containing the above pages in that order and a social menu

Placeholder images were used instead of photographs for now.

**Comment by LittleBigThing** [comment]
Hi, I've just updated the PR to the content on the [demo site's front page](https://2019.wordpress.net/). Except for the images, they are still placeholders, since I am not sure about the sources and the licenses.

Further, I am not sure how to port PRs over to Trac or convert them to patches. I can start by creating a ticket.

**Comment by allancole** [comment]
Hi @LittleBigThing, I don’t see an issue for this on Trac, so I’ll go ahead and take care of it and work out a patch for you. 👍

**Comment by allancole** [comment]
I've moved this PR to Trac as a patch here:

https://core.trac.wordpress.org/ticket/45927

I'll close this issue for now, and we can continue discussion over in that thread. Thanks!

**Pull request closed without merging**
